"""Last login added

Revision ID: 787867d0a91f
Revises: d349e15e8b59
Create Date: 2025-02-17 19:27:58.553332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787867d0a91f'
down_revision = 'd349e15e8b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
