"""company contact bank model added

Revision ID: c8a6cfb71880
Revises: 787867d0a91f
Create Date: 2025-02-18 16:51:36.138000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a6cfb71880'
down_revision = '787867d0a91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('ifsc_code', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('company_reg_number', sa.String(length=50), nullable=False),
    sa.Column('date_of_incorporation', sa.Date(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('pan_number', sa.String(length=50), nullable=True),
    sa.Column('gst_certificate_upload', sa.String(length=255), nullable=True),
    sa.Column('years_in_business', sa.Integer(), nullable=False),
    sa.Column('current_clients', sa.Text(), nullable=True),
    sa.Column('preferred_payment_terms', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_reg_number'),
    sa.UniqueConstraint('gst_number'),
    sa.UniqueConstraint('pan_number')
    )
    op.create_table('contact_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('alternate_contact_number', sa.String(length=15), nullable=True),
    sa.Column('adhar_card', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adhar_card')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_details')
    op.drop_table('company')
    op.drop_table('bank_details')
    # ### end Alembic commands ###
